### ISSUE TITLE
数据库配置

### ISSUE THREAD

**Issue by chinallong** [29DCH/OnlineMall#7]
你好，能不能请问一下您的**数据库配置**在哪里配的呢，我找了好久都没找到，如果能告知，非常感谢**

**Comment by 29DCH** [comment]
mall.sql文件导入到本地数据库
再在项目配置文件里面修改数据库参数，比如用户名、密码啥的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MingHanYan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 凌晨2:29
收件人:&nbsp;"29DCH/OnlineMall"<OnlineMall@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[29DCH/OnlineMall] 数据库配置 (#7)




你好，能不能请问一下您的数据库配置在哪里配的呢，我找了好久都没找到，如果能告知，非常感谢**

**Comment by chinallong** [comment]
哦哦，谢谢了
