### ISSUE TITLE
首页运行问题

### ISSUE THREAD

**Issue by yellow-tiger98** [29DCH/OnlineMall#9]
进入首页时报错，ERROR 15848 --- [nio-8080-exec-3] o.thymeleaf.templateparser.ErrorHandler  : [THYMELEAF][http-nio-8080-exec-3] Fatal error during parsing，请问有什么解决办法吗？谢谢

**Comment by hiahiawei** [comment]
你好，我也是这个错误，说是div没有闭合，具体位置在哪里你有找到吗

**Comment by yellow-tiger98** [comment]
> 你好，我也是这个错误，说是div没有闭合，具体位置在哪里你有找到吗

我是百度解决的，时间有点久忘记了，似乎是在配置文件中更改template的配置信息解决的

**Comment by hiahiawei** [comment]
你好，你的项目还在吗，能不能发我一份



---原始邮件---
发件人: "yellow-tiger98"<notifications@github.com&gt;
发送时间: 2020年5月10日(周日) 下午2:36
收件人: "29DCH/OnlineMall"<OnlineMall@noreply.github.com&gt;;
抄送: "海底造火箭"<2392475234@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [29DCH/OnlineMall] 首页运行问题 (#9)




  
你好，我也是这个错误，说是div没有闭合，具体位置在哪里你有找到吗
  
我是百度解决的，时间有点久忘记了，似乎是在配置文件中更改template的配置信息解决的

**Comment by hiahiawei** [comment]
解决了，谢谢，麻烦你了。



---原始邮件---
发件人: "yellow-tiger98"<notifications@github.com&gt;
发送时间: 2020年5月10日(周日) 下午2:36
收件人: "29DCH/OnlineMall"<OnlineMall@noreply.github.com&gt;;
抄送: "海底造火箭"<2392475234@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [29DCH/OnlineMall] 首页运行问题 (#9)




  
你好，我也是这个错误，说是div没有闭合，具体位置在哪里你有找到吗
  
我是百度解决的，时间有点久忘记了，似乎是在配置文件中更改template的配置信息解决的
